version: '3.9'

services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: "#!{DATABASE_USER}!#"
      POSTGRES_PASSWORD: "#!{DATABASE_PASSWORD}!#"
      POSTGRES_DB: "#!{DATABASE_NAME}!#"
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data
    networks:
      - challenge

  liquibase:
    build:
      context: ./database/
      dockerfile: Dockerfile
    depends_on:
      - db
    networks:
      - challenge

  migration:
    build:
      context: ./migration-pipeline/
      dockerfile: Dockerfile
    depends_on:
      - db
      - liquibase
    environment:
      POSTGRES_DB: #!{DATABASE_NAME}!#
      POSTGRES_USER: #!{DATABASE_USER}!#
      POSTGRES_PASSWORD: #!{DATABASE_PASSWORD}!#
      POSTGRES_HOST: db
    networks:
      - challenge

networks:
  challenge:
    driver: bridge
