--changeset rollback:1 delete all tables
DROP TABLE IF EXISTS employee CASCADE;
DROP TABLE IF EXISTS job CASCADE;
DROP TABLE IF EXISTS department CASCADE;
DROP TABLE IF EXISTS task CASCADE;
DROP TABLE IF EXISTS task_status CASCADE;
DROP TABLE IF EXISTS task_type CASCADE;
