#!/bin/sh

set -o errexit
set -o nounset

export PYTHONPATH='/code'

cd $PYTHONPATH

ENVIRONMENT="#!{ENVIRONMENT}!#"

if [ "$ENVIRONMENT" = "local" ]; then
    EXEC_COMMAND="dev"
else
    EXEC_COMMAND="run"
fi


fastapi $EXEC_COMMAND app/main.py --host 0.0.0.0 --port 8888
